<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>e</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2a4df000-c630-4d0c-b412-6368157e5b01</testSuiteGuid>
   <testCaseLink>
      <guid>bb1f4e8f-a89a-41fb-b83c-463d4bdb2669</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/saucelab/Scenario/login users</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8ed32924-9fb0-4264-9ff1-f07c5596f1dd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login xls</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8ed32924-9fb0-4264-9ff1-f07c5596f1dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>0f5ab9d5-42cc-4fe0-926f-b70d289fa775</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8ed32924-9fb0-4264-9ff1-f07c5596f1dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected</value>
         <variableId>d7224c38-df7d-4e81-a4b6-a5017ffdafc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8ed32924-9fb0-4264-9ff1-f07c5596f1dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tcName</value>
         <variableId>b16464d1-7d5c-40f9-942b-1eb9204c4746</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
