<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_message</name>
   <tag></tag>
   <elementGuidId>320031f7-fe4e-433d-83a5-b8554827933e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h3[@data-test=&quot;error&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h3[@data-test=&quot;error&quot;]</value>
      <webElementGuid>b90eb173-4325-4eb5-ae22-de1bcbcdc972</webElementGuid>
   </webElementProperties>
</WebElementEntity>
