<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>out</name>
   <tag></tag>
   <elementGuidId>c7c5dcd7-d678-460d-9dde-3bb7b83bc9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='sciOutPut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='sciOutPut']</value>
      <webElementGuid>312e95b8-60ae-4a1a-bb08-b71d013fecc9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
